name: eacnative
bundle_id: com.eac.eacnative

# Channels to look for any specific libraries
channels:
  - codelv

# App dependencies to be installed
dependencies:
  - python<3
  - enaml-native

# Exclude unused packages and libs using glob patterns here.
# Only the ones required by enaml-native are left in by default.
# If you need to use a module (ex json) then remove lib._json.so
# from this list so it does not get exlcuded. You can also add specific
# exclusions under ios and android.
excluded:
  # Packages
  - idlelib
  - ensurepip
  - distutils
  - lib2to3
  - pydoc_data
  - hotshot
  - site-packages/enaml/qt
  - site-packages/enaml/workbench
  - site-packages/enaml/*lib
  - site-packages/enaml/scint*

  - lib._cod*
  - lib._element*
  - lib.cmath.so
  - lib.termios.so
  # - lib._multi*
  - lib.mmap*
  - lib._hotshot.so
  - lib._ssl.so
  - lib._sqlite3.so
  - lib.pyexpat.so
  - lib.strop.so
  - lib.syslog.so
  - lib.enaml.*ext.so
  #- lib._md5.so
  #- lib._sha*.so
  #- lib._json.so
  #- lib._csv.so
  #- lib.cPickle.so

# Android specific configuration
android:
  ndk: /Users/youpsla/Library/Android/sdk/ndk-bundle/
  targets:
    #- x86_64
    #- x86
    #- arm
    - arm64
  excluded:
    - lib._ctypes.so

# iOS specific configuration
ios:
  targets:
    - iphoneos
    - iphonesimulator
